/*
 * Copyright 2013-2015, Teradata, Inc. All rights reserved.
 */

package com.teradata.test.context;

/**
 * Interface for invocation of tests in dsl defined context.
 */
public interface ContextRunnable<T>
{
    /**
     * Method invoked in given context T
     *
     * @param context context generated by {@link ContextProvider#setup}
     */
    void run(T context);
}
