FROM teradatalabs/centos6-java8-oracle
MAINTAINER Grzegorz Kokosiński <grzegorz.kokosinksi@teradata.com>

RUN curl -SL http://central.maven.org/maven2/com/facebook/presto/presto-cli/0.157/presto-cli-0.157-executable.jar -o presto-cli.jar

