version: '2'
services:
  hadoop-master:
    hostname: hadoop-master
    image: 'prestodb/hdp2.5-hive:1'
    ports:
      - '1080:1080'
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'

  psql1:
    hostname: psql1
    image: 'postgres'
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: blah
      POSTGRES_PASSWORD: blah

  psql2:
    hostname: psql2
    image: 'postgres'
    ports:
      - '15433:5432'
    environment:
      POSTGRES_USER: blah
      POSTGRES_PASSWORD: blah

  cassandra:
    hostname: cassandra
    image: 'cassandra:2.1.15'
    ports:
      - '9042:9042'
      - '9160:9160'

  ssh:
    hostname: ssh
    build: 'ssh'
    ports:
      - '2222:22'

  presto-master:
    hostname: presto-master
    build: 'presto-server'
    ports: 
      - '8080:8080'
    depends_on:
      - 'cassandra'
      - 'hadoop-master'
      - 'psql1'
      - 'psql2'

  presto-cli:
    build: 'presto-cli'
    depends_on:
      - 'presto-master'

  runner:
    image: 'prestodb/centos6-oj8:1'
    ports:
      - '5005:5005'
    volumes:
      - '..:/workspace'
    depends_on:
      - 'presto-master'

